apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: apptorney-backend-deployment
  name: apptorney-backend-deployment
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/apptorney-backend-deployment
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: apptorney-backend-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: apptorney-backend-deployment
    spec:
      containers:
      - image: uk.icr.io/apptorney-images/apptorney-backend:1
        imagePullPolicy: IfNotPresent
        name: apptorney-backend-deployment
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: MONGODB_CONNECTION_URL
          valueFrom:
            secretKeyRef:
                name: mongo-url
                key: MONGODB_CONNECTION_URL
        - name: ca_certificate_base64
          valueFrom:
            secretKeyRef:
                name: mongo-certificate
                key: ca_certificate_base64
        - name: NODE_ENV
          value: production
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}