# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'apptorney' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'Crashlytics'
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'apptorneyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'apptorney App Store' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for apptorney App Store

end
