# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'apptorney' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'Crashlytics'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Windless', '~> 0.1.5'
  pod 'paper-onboarding'
  pod 'PhoneNumberKit', '~> 2.1'
  pod 'MaterialComponents/Snackbar'
  

  target 'apptorneyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
