name: apptorney
options:
  bundleIdPrefix: com.apptorney
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    GENERATE_INFOPLIST_FILE: YES
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
targets:
  apptorney:
    type: application
    platform: iOS
    sources:
      - path: apptorney
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.apptorney.swiftui
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: Apptorney
    info:
      path: apptorney/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
