'use strict'
angular.module('apptorney')
.directive('setFocus', function(){
  return{
      scope: {setFocus: '='},
      link: function(scope, element){
         if(scope.setFocus) element[0].focus();
      }
  };
})
.controller('CasesController',function ($scope, $timeout, Court, Case, Legislation, Work,CaseLegislations, CaseCases, CaseWorks, AreaOfLaw,Jurisdiction, Location, baseURL, filterFilter) {
    console.log("xxx---->");










         $scope.message = "Loading data. Please wait...";
         $scope.filtered = false;
         $scope.saved = false;
         $scope.returned = false;
         $scope.showCases = false;
         $scope.cases = [];
         $scope.dirtyFields = [];
         $scope.currentCase = {};
         $scope.case = {};
         $scope.case.parties = {};
         $scope.case.citation = {};
         $scope.case.defendants = [];
         $scope.case.plaintiffs = [];
         $scope.plaintiff = {};
         $scope.defendant = {};
         $scope.appearance = {};
         $scope.judge = {};
         $scope.case.appearancesForDefendants = [];
         $scope.case.appearancesForPlaintiffs = [];
         $scope.case.parties.selectedPlaintiffAdvocates = [];
         $scope.legislations = [];
         $scope.saveStatus = 0;
         $scope.caseStab = {};
         $scope.legislationStab = {};
         $scope.workStab = {};
         $scope.queries={};
         $scope.caseReferences = [];
         $scope.legislationReferences = [];
         $scope.workReferences = [];


         $scope.courts = [];
         $scope.court = {};

         $scope.locations = [];
         $scope.location = {};


         $scope.jurisdictions = [];
         $scope.jurisdiction = {};

         $scope.areaOfLaw = {};
         $scope.areasOfLaw = [];

         $scope.case.coram = [];
         $scope.totalPages = 0;
         $scope.itemsPerPage = 100;
         $scope.totalCases = 0;










         $scope.setItemsPerPage = function(number){
           $scope.itemsPerPage = number;
         }

         $scope.createStab = function(newCase){

           if (typeof newCase === 'string'){
             var plaintiff = "";
             var defendant = "";
             var separator = 0;
             if (newCase.indexOf("Vs")!==-1){
               separator = newCase.indexOf("Vs");
             }
             else if (newCase.indexOf("vs")!==-1){
               separator = newCase.indexOf("vs");
             }
             else if (newCase.indexOf("VS")!==-1){
               separator = newCase.indexOf("VS");
             }

             console.info("Separator is ", separator);
             plaintiff = newCase.substring(0,separator-1);
             defendant = newCase.substring(separator+3, newCase.length);

             $scope.caseStab.plaintiffs = [];
             $scope.caseStab.defendants = [];

             $scope.caseStab.plaintiffs.push({name:plaintiff});
             $scope.caseStab.defendants.push({name:defendant});
             $scope.caseStab.name = newCase;
             $scope.caseStab.autogenerated = true;



             console.info("Stab is", $scope.caseStab);
           }

         }


         $scope.$watch('queries.caseReferencesQuery', function () {
               console.log("Watching Case References...");

          });






         $scope.saveStab = function(event){
           console.info("This is the detected text", $scope.queries.caseReferencesQuery);
           $scope.createStab($scope.queries.caseReferencesQuery);
           if(event.which === 13){
              console.log("Savng Stab...");

              Case.upsert($scope.caseStab,
                  function(aCase){
                      var caseArray = [];




                      $scope.caseReferences = Case.find({
                                 filter:{fields:{
                                    defendants:true,
                                    plaintiffs:true,
                                    id:true

                                 },
                                 where: {
                                   id: aCase.id
                                 }
                               }},
                                 function(cases) {

                                   cases.forEach(function(aCase){

                                     aCase.accuser = "";
                                     aCase.accused = "";
                                     if(aCase.plaintiffs.length > 1){
                                       aCase.accuser = aCase.plaintiffs[0].name + " and Others";
                                     }
                                     else {
                                       aCase.accuser = aCase.plaintiffs[0].name;
                                     }

                                     if(aCase.defendants.length > 1){
                                       aCase.accused = aCase.defendants[0].name + " and Others";
                                     }
                                     else {
                                       aCase.accused = aCase.defendants[0].name;
                                     }

                                     aCase.name = aCase.accuser + " Vs "+aCase.accused;

                                   });

                                   console.info("Retained | Returned Case References", aCase);

                                 },
                                 function(errorResponse) { }
                               );

                  },
                  function(error){

                  }
              );


           }

         }


         $scope.createLegislationStab = function(newLegislation){
           if (typeof newLegislation === 'string'){
             $scope.legislationStab.legislationName = newLegislation;
             $scope.legislationStab.autogenerated = true;

           }
         }

         $scope.saveLegislationStab = function(event){
            $scope.createLegislationStab($scope.queries.legislationReferencesQuery);
            if(event.which === 13){
              Legislation.upsert($scope.legislationStab,
                  function(legislation){
                    $scope.legislationReferences.push(legislation);
                    //$scope.case.legislationsReferedTo.push(legislation);
                  },
                  function(error){

                  }
              )
            }
         }


         $scope.createWorkStab = function(newWork){
           if (typeof newWork === 'string'){
             $scope.workStab.name = newWork;
             $scope.workStab.autogenerated = true;

           }
         }

         $scope.saveWorkStab = function(event){
            $scope.createWorkStab($scope.queries.workReferencesQuery);
            if(event.which === 13){
              Work.upsert($scope.workStab,
                  function(work){
                    $scope.workReferences.push(work);
                    //$scope.case.legislationsReferedTo.push(legislation);
                  },
                  function(error){

                  }
              )
            }
         }





         $scope.getTotalCases = function(){
           Case.count({}, function(result){
             $scope.totalCases = result.count;
             $scope.totalPages = Math.ceil($scope.totalCases/$scope.itemsPerPage);
             console.info("Total number of pages = ", $scope.totalPages);
           },function(error){});
         }

        $scope.getTotalCases();


         $scope.newCase = function(){
           $scope.case.isNew = true;
           $scope.case = {};
           $scope.case.parties = {};
           $scope.case.citation = {};
           $scope.case.defendants = [];
           $scope.case.plaintiffs = [];
           $scope.case.coram = [];
           $scope.plaintiff = {};
           $scope.defendant = {};
           $scope.appearance = {};
           $scope.judge = {};
           $scope.case.appearancesForDefendants = [];
           $scope.case.appearancesForPlaintiffs = [];
           $scope.case.parties.selectedPlaintiffAdvocates = [];
           $scope.case.legislationsReferedTo = [];
           $scope.case.workReferedTo = [];
           $scope.case.casesReferedTo = [];
           $scope.addCaseParties();

         }

        /*  $scope.$watch('query', function () {
              if($scope.query.length > 4){
                $scope.bigCurrentPage = 0;
              }

          });

*/
          $scope.$watch('itemsPerPage', function () {
               $scope.getTotalCases();


               $scope.cases = Case.find({
                 filter:{fields:{
                    appearancesForPlaintiffs:false,
                    appearancesForDefendants:false,
                    legislationsReferedTo:false,
                    casesReferedTo:false,
                    workReferedTo:false,
                    summaryOfFacts:false,
                    summaryOfRuling:false,
                    judgement:false,
                    court:false,
                    areaOfLawId:false,
                    coram:false,
                    courtId:false,
                    defendantSynonymId:false,
                    jurisdictionId:false,
                    locationId:false,
                    plaintiffSynonymId:false

                 },
                 order: "citation.year DESC",
                 limit:$scope.itemsPerPage,
                 skip:($scope.bigCurrentPage-1)*$scope.itemsPerPage
               }},
                 function(cases) {

                   cases.forEach(function(aCase){
                    //console.info("Case Plaintiffs", aCase.plaintiffs);
                     aCase.accuser = "";
                     aCase.accused = "";



                     if(aCase.plaintiffs.length > 1){
                       aCase.accuser = aCase.plaintiffs[0].name + " and Others";
                     }
                     else {
                       aCase.accuser = aCase.plaintiffs[0].name;
                     }

                     if(aCase.defendants.length > 1){
                       aCase.accused = aCase.defendants[0].name + " and Others";
                     }
                     else {
                       aCase.accused = aCase.defendants[0].name;
                     }

                     aCase.name = aCase.accuser + " Vs. "+aCase.accused;

                   });



                   $scope.cases = cases;



                   $scope.returned = true;
                   $scope.showCases = true;

                 },
                 function(errorResponse) { }
               );


         });



         $scope.$watch('bigCurrentPage', function () {
            if($scope.bigCurrentPage == 0){
              $scope.cases = Case.find({
                filter:{where: {
                  name: $scope.query
                },
                fields:{
                   appearancesForPlaintiffs:false,
                   appearancesForDefendants:false,
                   legislationsReferedTo:false,
                   casesReferedTo:false,
                   workReferedTo:false,
                   summaryOfFacts:false,
                   summaryOfRuling:false,
                   judgement:false,
                   court:false,
                   areaOfLawId:false,
                   coram:false,
                   courtId:false,
                   defendantSynonymId:false,
                   jurisdictionId:false,
                   locationId:false,
                   plaintiffSynonymId:false

                }
              }},
                function(cases) {

                  cases.forEach(function(aCase){
                   console.log("xxxxxxxxxx----->");
                    aCase.accuser = "";
                    aCase.accused = "";
                    if(aCase.plaintiffs.length > 1){
                      aCase.accuser = aCase.plaintiffs[0].name + " and Others";
                    }
                    else {
                      aCase.accuser = aCase.plaintiffs[0].name;
                    }

                    if(aCase.defendants.length > 1){
                      aCase.accused = aCase.defendants[0].name + " and Others";
                    }
                    else {
                      aCase.accused = aCase.defendants[0].name;
                    }

                    aCase.name = aCase.accuser + " Vs. "+aCase.accused;

                  });



                  $scope.cases = cases;



                  $scope.returned = true;
                  $scope.showCases = true;

                },
                function(errorResponse) { }
              );
            }
            else {
              $scope.cases = Case.find({
                filter:{fields:{
                   appearancesForPlaintiffs:false,
                   appearancesForDefendants:false,
                   legislationsReferedTo:false,
                   casesReferedTo:false,
                   workReferedTo:false,
                   summaryOfFacts:false,
                   summaryOfRuling:false,
                   judgement:false,
                   court:false,
                   areaOfLawId:false,
                   coram:false,
                   courtId:false,
                   defendantSynonymId:false,
                   jurisdictionId:false,
                   locationId:false,
                   plaintiffSynonymId:false

                },
                order: "citation.year DESC",
                limit:$scope.itemsPerPage,
                skip:($scope.bigCurrentPage-1)*$scope.itemsPerPage
              }},
                function(cases) {

                  cases.forEach(function(aCase){
                   console.log("xxxxxxxxxx----->");
                    aCase.accuser = "";
                    aCase.accused = "";
                    if(aCase.plaintiffs.length > 1){
                      aCase.accuser = aCase.plaintiffs[0].name + " and Others";
                    }
                    else {
                      aCase.accuser = aCase.plaintiffs[0].name;
                    }

                    if(aCase.defendants.length > 1){
                      aCase.accused = aCase.defendants[0].name + " and Others";
                    }
                    else {
                      aCase.accused = aCase.defendants[0].name;
                    }

                    aCase.name = aCase.accuser + " Vs. "+aCase.accused;

                  });



                  $scope.cases = cases;



                  $scope.returned = true;
                  $scope.showCases = true;

                },
                function(errorResponse) { }
              );
            }

        });




         $scope.addCaseParties = function(){
           $scope.case.defendants.push(angular.copy($scope.defendant));
           $scope.case.plaintiffs.push(angular.copy($scope.plaintiff));
           $scope.case.appearancesForPlaintiffs.push(angular.copy($scope.appearance));
           $scope.case.appearancesForDefendants.push(angular.copy($scope.appearance));
           $scope.case.coram.push(angular.copy($scope.judge));


         }

         $scope.addCaseParties();

         $scope.addDefendant = function(event){
           if(event.which === 13){
              $scope.case.defendants.push(angular.copy($scope.defendant));

           }
         }

         $scope.addPlaintiff = function(event){
           if(event.which === 13){
              $scope.case.plaintiffs.push(angular.copy($scope.plaintiff));
           }

         }

         $scope.addPlaintiffAdvocate = function(event){
           if(event.which === 13){
              $scope.case.appearancesForPlaintiffs.push(angular.copy($scope.appearance));

           }

         }

         $scope.addDefendantAdvocate = function(event){
           if(event.which === 13){
              $scope.case.appearancesForDefendants.push(angular.copy($scope.appearance));

           }

         }

         $scope.addJudge = function(event){
           if(event.which === 13){
              $scope.case.coram.push(angular.copy($scope.judge));

           }

         }






         $scope.areasOfLaw = AreaOfLaw.find(
           function(list) {
             console.log(list);
             $scope.areasReturned = true;
             $scope.showAreas = true;
           },
           function(errorResponse) { }
         );

         $scope.saveAreaOfLaw = function(){
           console.log($scope.areaOfLaw);
           AreaOfLaw.upsert($scope.areaOfLaw,
             function(area){
               $scope.areasOfLaw.push(area);
             },
             function(errorResponse){

             }
           );

           $("#addAreaOfLawModal").modal("hide");

         }


         $scope.locations = Location.find(
           function(list) {
             console.log(list);
             $scope.locationsReturned = true;
             $scope.showLocations = true;
           },
           function(errorResponse) { }
         );

         $scope.saveLocation = function(){
           console.log($scope.location);
           Location.upsert($scope.location,
             function(location){
               $scope.locations.push(location);
             },
             function(errorResponse){

             }
           );

           $("#addLocationModal").modal("hide");

         }

         $scope.deleteLocation = function(locationID){

           Location.deleteById({ id: locationID })
           .$promise
           .then(function() {
             //console.log('deleted');
             $scope.locations.forEach(function(location){
               if(location.id == locationID){
                 $scope.locations.splice($scope.locations.indexOf(location),1);

               }
             });
           });

         }


         $scope.jurisdictions = Jurisdiction.find(
           function(list) {
             console.log(list);
             $scope.jurisdictionsReturned = true;
             $scope.showJurisdictions = true;
           },
           function(errorResponse) { }
         );

         $scope.saveJurisdiction = function(){
           console.log($scope.jurisdiction);
           Jurisdiction.upsert($scope.jurisdiction,
             function(jurisdiction){
               $scope.jurisdictions.push(jurisdiction);
             },
             function(errorResponse){

             }
           );

           $("#addJurisdictionModal").modal("hide");

         }

         $scope.deleteJurisdiction = function(jurisdictionID){

           Jurisdiction.deleteById({ id: jurisdictionID })
           .$promise
           .then(function() {
             //console.log('deleted');
             $scope.jurisdictions.forEach(function(jurisdiction){
               if(jurisdiction.id == jurisdictionID){
                 $scope.jurisdictions.splice($scope.jurisdictions.indexOf(jurisdiction),1);

               }
             });
           });

         }



         $scope.saveCase = function(){
                 console.info("Case Details", $scope.case);
                 $scope.saveStatus = 1;

                 Case.upsert($scope.case,
                     function(aCase){
                         $scope.case.legislationsReferedTo.forEach(function(legislation){
                           CaseLegislations.create({
                             caseId: aCase.id,
                             legislationId: legislation.id
                           }, function(res){}, function(err){});

                         });

                         $scope.case.casesReferedTo.forEach(function(reference){
                           CaseCases.create({
                             caseId: aCase.id,
                             caseReferedToId: reference.id
                           }, function(res){}, function(err){});

                         })

                         $scope.case.workReferedTo.forEach(function(reference){
                           CaseWorks.create({
                             caseId: aCase.id,
                             workId: reference.id
                           }, function(res){}, function(err){});



                         })

                         $scope.saveStatus = 2;
                         setTimeout(function(){ $scope.saveStatus = 0; console.log("Save Status = " + $scope.saveStatus); $("#applicationForm").click(); }, 10000);






                         if($scope.case.isNew == true){
                           $scope.cases.push(aCase);
                         }


                     },
                     function(errorResponse){

                     }
                 );




         }







         $scope.generateName = function(aCase){
            aCase.accuser = "";
            aCase.accused = "";
            if(aCase.plaintiffs.length > 1){
              aCase.accuser = aCase.plaintiffs[0].name + " and Others";
            }
            else {
              aCase.accuser = aCase.plaintiffs[0].name;
            }

            if(aCase.defendants.length > 1){
              aCase.accused = aCase.defendants[0].name + " and Others";
            }
            else {
              aCase.accused = aCase.defendants[0].name;
            }

            return aCase.name = aCase.accuser + " Vs. "+aCase.accused;
         }



         $scope.openCase = function(aCase){


           $scope.viewMode = true;
           Case.find({
             filter:{include: [{
               relation: 'plaintiffSynonym', // include the owner object
               scope: { // further filter the owner object
                 fields: ['synonym'] // only show two fields
               }},
               {relation: 'defendantSynonym', // include the owner object
               scope: { // further filter the owner object
                 fields: ['synonym'] // only show two fields
               }},
               {relation: 'court', // include the owner object
               scope: { // further filter the owner object
                 fields: ['name'] // only show two fields
               }},
               {relation: 'location', // include the owner object
               scope: { // further filter the owner object
                 fields: ['name'] // only show two fields
               }},
               {relation: 'jurisdiction', // include the owner object
               scope: { // further filter the owner object
                 fields: ['name'] // only show two fields
               }},
               {relation: 'legislationsReferedTo', // include the owner object
               scope: { // further filter the owner object
                 fields: ['legislationName'] // only show two fields
               }},
               {relation: 'casesReferedTo', // include the owner object
               scope: { // further filter the owner object
                 fields: ['plaintiffs','defendants'] // only show two fields
               }},
               {relation: 'workReferedTo', // include the owner object
               scope: { // further filter the owner object
                 fields: ['name'] // only show two fields
               }},
               {relation: 'areaOfLaw', // include the owner object
               scope: { // further filter the owner object
                 fields: ['name'] // only show two fields
               }}
             ],

             where: {
               id: aCase.id
             }
             }},
             function(list) {

               $scope.case = list[0];

               $scope.case.isNew = false;
               $scope.case.citation.year = parseInt($scope.case.citation.year);

               //Generate Names for Reference Field in view

               $scope.case.casesReferedTo.forEach(function(reference){
                 reference.name=$scope.generateName(reference);
                 console.info("Case reference",  reference);
               });

               $scope.returned = true;

             },
             function(errorResponse) { }
           );





         }

         $scope.addCaseReference = function(aCase){
           $scope.case.casesReferedTo.push(aCase);
         }


         $scope.addLegislationReference = function(legislation){
           $scope.case.legislationsReferedTo.push(legislation);
         }


         $scope.addWorkReference = function(work){
           $scope.case.workReferedTo.push(work);
         }





         $scope.openLegislationReferences = function(){
            setTimeout(function(){
              $scope.legislationReferences = Legislation.find({
                         filter:{fields:{
                            legislationName:true,
                            id:true

                         }

                       }},
                         function(legislations) {},
                         function(error){}
             );
           }, 3000);

         }

         $scope.openCaseReferences = function(){




                $scope.caseReferences = Case.find({
                           filter:{fields:{
                              defendants:true,
                              plaintiffs:true,
                              id:true

                           }

                         }},
                           function(cases) {

                             cases.forEach(function(aCase){
                              console.log("xxxxxxxxxx----->");
                               aCase.accuser = "";
                               aCase.accused = "";
                               if(aCase.plaintiffs.length > 1){
                                 aCase.accuser = aCase.plaintiffs[0].name + " and Others";
                               }
                               else {
                                 aCase.accuser = aCase.plaintiffs[0].name;
                               }

                               if(aCase.defendants.length > 1){
                                 aCase.accused = aCase.defendants[0].name + " and Others";
                               }
                               else {
                                 aCase.accused = aCase.defendants[0].name;
                               }

                               aCase.name = aCase.accuser + " Vs. "+aCase.accused;

                             });

                             console.info("Case References", $scope.caseReferences);

                           },
                           function(errorResponse) { }
                         );
         }

         $scope.openWorkReferences = function(){
               $scope.workReferences = Work.find({
                          filter:{fields:{
                             name:true,
                             id:true

                          }

                        }},
                          function(work) {},
                          function(error){}
              );
         }














  });


  var openAddAreaOfLaw = function(){
    //$("#addAreaOfLawModal").modal();
    console.log("opened");
    $('#addAreaOfLawModal').appendTo("body").modal('show');
  }

  var openAddCourt = function(){
    //$("#addAreaOfLawModal").modal();
    $('#addCourtModal').appendTo("body").modal('show');
  }

  var openAddLegislation = function(){
    //$("#addAreaOfLawModal").modal();
    $('#addLegislationModal').appendTo("body").modal('show');
  }
